In [183]:
import numpy as np
import pandas as pd

In [184]:
#exporta o arquivo csv
df = pd.read_csv("players.csv")

In [185]:
#mostra o cabeçario do DataFrame
df.head

<bound method NDFrame.head of        player_id       common_name   first_name        last_name  \
0         227203   Alexia Putellas       Alexia  Putellas Segura
1         231747               NaN       Kylian           Mbappé
2         239085               NaN       Erling          Haaland
3         192119               NaN      Thibaut         Courtois
4         202126               NaN        Harry             Kane
...          ...               ...          ...              ...
19784      85140  Park Byeong Chan  Byeong Chan             Park
19785      85153         Kim Ji Ho        Ji Ho              Kim
19786     259737               NaN       Haobam            Singh
19787     275674          Ma Haoqi        Haoqi               Ma
19788     275675       Ning Fangze       Fangze             Ning

       overall_rating position alternate_positions               club  \
0                  91       CM              CAM ST        London City
1                  91       ST                  LW        Real Madrid
2                  91       ST                 NaN    Manchester City
3                  90       GK                 NaN        Real Madrid
4                  90       ST                 NaN  FC Bayern München
...               ...      ...                 ...                ...
19784              47      CDM                  CM       Daejeon Hana
19785              47       RW                  RM       Daejeon Hana
19786              47       CM             CAM CDM             FC Goa
19787              47       RM                  RW       Zhejiang Pro
19788              47       LW                  LM       Zhejiang Pro

                 league     nationality  ... defending_awareness  \
0          Barclays WSL           Spain  ...                  60
1      LALIGA EA SPORTS          France  ...                  15
2        Premier League          Norway  ...                  42
3      LALIGA EA SPORTS         Belgium  ...                  20
4            Bundesliga         England  ...                  46
...                 ...             ...  ...                 ...
19784        K League 1  Korea Republic  ...                  42
19785        K League 1  Korea Republic  ...                  19
19786               ISL           India  ...                  39
19787               CSL        China PR  ...                  15
19788               CSL        China PR  ...                  32

      defending_standing_tackle  defending_sliding_tackle  goalkeeping_diving  \
0                            82                        64                  15
1                            34                        24                  13
2                            47                        33                   7
3                            18                        16                  87
4                            44                        42                   8
...                         ...                       ...                 ...
19784                        40                        50                  13
19785                        22                        29                   9
19786                        43                        41                  14
19787                        22                        26                   9
19788                        40                        43                   7

       goalkeeping_handling  goalkeeping_kicking goalkeeping_positioning  \
0                        17                   11                      15
1                         5                    7                      11
2                        14                   13                      11
3                        89                   78                      90
4                        10                   11                      14
...                     ...                  ...                     ...
19784                     9                    6                       9
19785                    13                    7                      11
19786                    12                   15                      14
19787                     8                    8                      12
19788                     9                    5                       5

      goalkeeping_reflexes  edition  snapshot_date
0                       10     fc27     2026-09-12
1                        6     fc27     2026-09-12
2                        7     fc27     2026-09-12
3                       90     fc27     2026-09-12
4                       11     fc27     2026-09-12
...                    ...      ...            ...
19784                    8     fc27     2026-09-12
19785                   13     fc27     2026-09-12
19786                    6     fc27     2026-09-12
19787                   12     fc27     2026-09-12
19788                   14     fc27     2026-09-12

[19789 rows x 60 columns]>

In [186]:
#copio uma das colunas dentro do DataFrame para criar uma Series
ser = df["nationality"].copy()

In [187]:
ser.head()

0      Spain
1     France
2     Norway
3    Belgium
4    England
Name: nationality, dtype: str

In [188]:
#numero de elementos distintos junto com os elementos
ser.unique()

<ArrowStringArray>
[              'Spain',              'France',              'Norway',
             'Belgium',             'England',             'Jamaica',
            'Portugal',           'Argentina',               'Italy',
              'Brazil',
 ...
           'Mauritius',             'Somalia',          'Montserrat',
 'São Tomé e Príncipe',           'Korea DPR',         'Afghanistan',
         'Puerto Rico',                'Oman',           'Gibraltar',
               'Yemen']
Length: 164, dtype: str

In [189]:
#apenas o número de elementos distintos
ser.nunique()

164

In [190]:
#numero de vezes que cada elemento aparece
ser.value_counts()

nationality
England                1527
Germany                1390
Spain                  1210
France                 1081
Argentina              1038
                       ...
São Tomé e Príncipe       1
Korea DPR                 1
Afghanistan               1
Oman                      1
Gibraltar                 1
Name: count, Length: 164, dtype: int64

In [191]:
#permite visualização de duas colunas
df[["nationality", "first_name"]]

          nationality   first_name
0               Spain       Alexia
1              France       Kylian
2              Norway       Erling
3             Belgium      Thibaut
4             England        Harry
...               ...          ...
19784  Korea Republic  Byeong Chan
19785  Korea Republic        Ji Ho
19786           India       Haobam
19787        China PR        Haoqi
19788        China PR       Fangze

[19789 rows x 2 columns]

In [192]:
#permite visualização da coluna, não muito recomendado
df.nationality

0                 Spain
1                France
2                Norway
3               Belgium
4               England
              ...
19784    Korea Republic
19785    Korea Republic
19786             India
19787          China PR
19788          China PR
Name: nationality, Length: 19789, dtype: str

In [193]:
#transforma a coluna escolhida em um indice
df.set_index("nationality")

,player_id,common_name,first_name,last_name,overall_rating,position,alternate_positions,club,league,gender,...,defending_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,edition,snapshot_date
nationality,,,,,,,,,,,,,,,,,,,,,
Spain,227203,Alexia Putellas,Alexia,Putellas Segura,91,CM,CAM ST,London City,Barclays WSL,Women's Football,...,60,82,64,15,17,11,15,10,fc27,2026-09-12
France,231747,NaN,Kylian,Mbappé,91,ST,LW,Real Madrid,LALIGA EA SPORTS,Men's Football,...,15,34,24,13,5,7,11,6,fc27,2026-09-12
Norway,239085,NaN,Erling,Haaland,91,ST,NaN,Manchester City,Premier League,Men's Football,...,42,47,33,7,14,13,11,7,fc27,2026-09-12
Belgium,192119,NaN,Thibaut,Courtois,90,GK,NaN,Real Madrid,LALIGA EA SPORTS,Men's Football,...,20,18,16,87,89,78,90,90,fc27,2026-09-12
England,202126,NaN,Harry,Kane,90,ST,NaN,FC Bayern München,Bundesliga,Men's Football,...,46,44,42,8,10,11,14,11,fc27,2026-09-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Korea Republic,85140,Park Byeong Chan,Byeong Chan,Park,47,CDM,CM,Daejeon Hana,K League 1,Men's Football,...,42,40,50,13,9,6,9,8,fc27,2026-09-12
Korea Republic,85153,Kim Ji Ho,Ji Ho,Kim,47,RW,RM,Daejeon Hana,K League 1,Men's Football,...,19,22,29,9,13,7,11,13,fc27,2026-09-12
India,259737,NaN,Haobam,Singh,47,CM,CAM CDM,FC Goa,ISL,Men's Football,...,39,43,41,14,12,15,14,6,fc27,2026-09-12
China PR,275674,Ma Haoqi,Haoqi,Ma,47,RM,RW,Zhejiang Pro,CSL,Men's Football,...,15,22,26,9,8,8,12,12,fc27,2026-09-12
China PR,275675,Ning Fangze,Fangze,Ning,47,LW,LM,Zhejiang Pro,CSL,Men's Football,...,32,40,43,7,9,5,5,14,fc27,2026-09-12

In [194]:
#cria uma nova coluna usando um array criado com valores aleatorios
df["Coluna_Demo"] = np.random.rand(19789, 1)
df

,player_id,common_name,first_name,last_name,overall_rating,position,alternate_positions,club,league,nationality,...,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,edition,snapshot_date,Coluna_Demo
0,227203,Alexia Putellas,Alexia,Putellas Segura,91,CM,CAM ST,London City,Barclays WSL,Spain,...,82,64,15,17,11,15,10,fc27,2026-09-12,0.493572
1,231747,NaN,Kylian,Mbappé,91,ST,LW,Real Madrid,LALIGA EA SPORTS,France,...,34,24,13,5,7,11,6,fc27,2026-09-12,0.963524
2,239085,NaN,Erling,Haaland,91,ST,NaN,Manchester City,Premier League,Norway,...,47,33,7,14,13,11,7,fc27,2026-09-12,0.688475
3,192119,NaN,Thibaut,Courtois,90,GK,NaN,Real Madrid,LALIGA EA SPORTS,Belgium,...,18,16,87,89,78,90,90,fc27,2026-09-12,0.155914
4,202126,NaN,Harry,Kane,90,ST,NaN,FC Bayern München,Bundesliga,England,...,44,42,8,10,11,14,11,fc27,2026-09-12,0.655665
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19784,85140,Park Byeong Chan,Byeong Chan,Park,47,CDM,CM,Daejeon Hana,K League 1,Korea Republic,...,40,50,13,9,6,9,8,fc27,2026-09-12,0.117119
19785,85153,Kim Ji Ho,Ji Ho,Kim,47,RW,RM,Daejeon Hana,K League 1,Korea Republic,...,22,29,9,13,7,11,13,fc27,2026-09-12,0.629946
19786,259737,NaN,Haobam,Singh,47,CM,CAM CDM,FC Goa,ISL,India,...,43,41,14,12,15,14,6,fc27,2026-09-12,0.617656
19787,275674,Ma Haoqi,Haoqi,Ma,47,RM,RW,Zhejiang Pro,CSL,China PR,...,22,26,9,8,8,12,12,fc27,2026-09-12,0.264665
19788,275675,Ning Fangze,Fangze,Ning,47,LW,LM,Zhejiang Pro,CSL,China PR,...,40,43,7,9,5,5,14,fc27,2026-09-12,0.816715

In [195]:
#crio dois arrays para criar unidimensionais para criar um DataFrame
arr1 = np.arange(0, 19789)
arr2 = np.arange(19789, 0, -1)
print(arr1)
print(arr2)

[    0     1     2 ... 19786 19787 19788]
[19789 19788 19787 ...     3     2     1]

In [196]:
ser1 = pd.Series(arr1)
ser2 = pd.Series(arr2)
ser1

0            0
1            1
2            2
3            3
4            4
         ...
19784    19784
19785    19785
19786    19786
19787    19787
19788    19788
Length: 19789, dtype: int64

In [197]:
ser2

0        19789
1        19788
2        19787
3        19786
4        19785
         ...
19784        5
19785        4
19786        3
19787        2
19788        1
Length: 19789, dtype: int64

In [198]:
#concateno as duas Series criadas em uma, usando o eixo x
ser3 = pd.concat([ser1, ser2], axis=1)
ser3

           0      1
0          0  19789
1          1  19788
2          2  19787
3          3  19786
4          4  19785
...      ...    ...
19784  19784      5
19785  19785      4
19786  19786      3
19787  19787      2
19788  19788      1

[19789 rows x 2 columns]

In [199]:
#Crio um DataFrame apartir da Series criada anteriormente
df2 = pd.DataFrame(ser3)
df2

           0      1
0          0  19789
1          1  19788
2          2  19787
3          3  19786
4          4  19785
...      ...    ...
19784  19784      5
19785  19785      4
19786  19786      3
19787  19787      2
19788  19788      1

[19789 rows x 2 columns]

In [200]:
#aplico uma função lambda em cada elemento dentro do DataFrame
df2.apply(lambda x: x*10)

            0       1
0           0  197890
1          10  197880
2          20  197870
3          30  197860
4          40  197850
...       ...     ...
19784  197840      50
19785  197850      40
19786  197860      30
19787  197870      20
19788  197880      10

[19789 rows x 2 columns]

In [201]:
#operação para ver os elementos do DataFrame menores que 100
df2[df2 < 100]

         0    1
0      0.0  NaN
1      1.0  NaN
2      2.0  NaN
3      3.0  NaN
4      4.0  NaN
...    ...  ...
19784  NaN  5.0
19785  NaN  4.0
19786  NaN  3.0
19787  NaN  2.0
19788  NaN  1.0

[19789 rows x 2 columns]

In [202]:
#faço a junção do df com o df2 com o método join
df.join(df2)

,player_id,common_name,first_name,last_name,overall_rating,position,alternate_positions,club,league,nationality,...,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,edition,snapshot_date,Coluna_Demo,0,1
0,227203,Alexia Putellas,Alexia,Putellas Segura,91,CM,CAM ST,London City,Barclays WSL,Spain,...,15,17,11,15,10,fc27,2026-09-12,0.493572,0,19789
1,231747,NaN,Kylian,Mbappé,91,ST,LW,Real Madrid,LALIGA EA SPORTS,France,...,13,5,7,11,6,fc27,2026-09-12,0.963524,1,19788
2,239085,NaN,Erling,Haaland,91,ST,NaN,Manchester City,Premier League,Norway,...,7,14,13,11,7,fc27,2026-09-12,0.688475,2,19787
3,192119,NaN,Thibaut,Courtois,90,GK,NaN,Real Madrid,LALIGA EA SPORTS,Belgium,...,87,89,78,90,90,fc27,2026-09-12,0.155914,3,19786
4,202126,NaN,Harry,Kane,90,ST,NaN,FC Bayern München,Bundesliga,England,...,8,10,11,14,11,fc27,2026-09-12,0.655665,4,19785
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19784,85140,Park Byeong Chan,Byeong Chan,Park,47,CDM,CM,Daejeon Hana,K League 1,Korea Republic,...,13,9,6,9,8,fc27,2026-09-12,0.117119,19784,5
19785,85153,Kim Ji Ho,Ji Ho,Kim,47,RW,RM,Daejeon Hana,K League 1,Korea Republic,...,9,13,7,11,13,fc27,2026-09-12,0.629946,19785,4
19786,259737,NaN,Haobam,Singh,47,CM,CAM CDM,FC Goa,ISL,India,...,14,12,15,14,6,fc27,2026-09-12,0.617656,19786,3
19787,275674,Ma Haoqi,Haoqi,Ma,47,RM,RW,Zhejiang Pro,CSL,China PR,...,9,8,8,12,12,fc27,2026-09-12,0.264665,19787,2
19788,275675,Ning Fangze,Fangze,Ning,47,LW,LM,Zhejiang Pro,CSL,China PR,...,7,9,5,5,14,fc27,2026-09-12,0.816715,19788,1

In [203]:
#aqui tem bastante dados nulos
df["common_name"]

0         Alexia Putellas
1                     NaN
2                     NaN
3                     NaN
4                     NaN
               ...
19784    Park Byeong Chan
19785           Kim Ji Ho
19786                 NaN
19787            Ma Haoqi
19788         Ning Fangze
Name: common_name, Length: 19789, dtype: str

In [204]:
#tratamento retirando colunas com dados nulos
df_op1 = df.dropna(axis=1)
df_op1

,player_id,first_name,last_name,overall_rating,position,club,league,nationality,gender,preferred_foot,...,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,edition,snapshot_date,Coluna_Demo
0,227203,Alexia,Putellas Segura,91,CM,London City,Barclays WSL,Spain,Women's Football,Left,...,82,64,15,17,11,15,10,fc27,2026-09-12,0.493572
1,231747,Kylian,Mbappé,91,ST,Real Madrid,LALIGA EA SPORTS,France,Men's Football,Right,...,34,24,13,5,7,11,6,fc27,2026-09-12,0.963524
2,239085,Erling,Haaland,91,ST,Manchester City,Premier League,Norway,Men's Football,Left,...,47,33,7,14,13,11,7,fc27,2026-09-12,0.688475
3,192119,Thibaut,Courtois,90,GK,Real Madrid,LALIGA EA SPORTS,Belgium,Men's Football,Left,...,18,16,87,89,78,90,90,fc27,2026-09-12,0.155914
4,202126,Harry,Kane,90,ST,FC Bayern München,Bundesliga,England,Men's Football,Right,...,44,42,8,10,11,14,11,fc27,2026-09-12,0.655665
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19784,85140,Byeong Chan,Park,47,CDM,Daejeon Hana,K League 1,Korea Republic,Men's Football,Right,...,40,50,13,9,6,9,8,fc27,2026-09-12,0.117119
19785,85153,Ji Ho,Kim,47,RW,Daejeon Hana,K League 1,Korea Republic,Men's Football,Right,...,22,29,9,13,7,11,13,fc27,2026-09-12,0.629946
19786,259737,Haobam,Singh,47,CM,FC Goa,ISL,India,Men's Football,Right,...,43,41,14,12,15,14,6,fc27,2026-09-12,0.617656
19787,275674,Haoqi,Ma,47,RM,Zhejiang Pro,CSL,China PR,Men's Football,Right,...,22,26,9,8,8,12,12,fc27,2026-09-12,0.264665
19788,275675,Fangze,Ning,47,LW,Zhejiang Pro,CSL,China PR,Men's Football,Right,...,40,43,7,9,5,5,14,fc27,2026-09-12,0.816715

In [205]:
#ao inves de remover, substitui o dado ausente com um valor padrão
df_op2 = df.fillna(value="Null")
df_op2["common_name"]

0         Alexia Putellas
1                    Null
2                    Null
3                    Null
4                    Null
               ...
19784    Park Byeong Chan
19785           Kim Ji Ho
19786                Null
19787            Ma Haoqi
19788         Ning Fangze
Name: common_name, Length: 19789, dtype: str

In [206]:
#retiro uma das colunas criadas para a prática
df.drop("Coluna_Demo", axis=1)

,player_id,common_name,first_name,last_name,overall_rating,position,alternate_positions,club,league,nationality,...,defending_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,edition,snapshot_date
0,227203,Alexia Putellas,Alexia,Putellas Segura,91,CM,CAM ST,London City,Barclays WSL,Spain,...,60,82,64,15,17,11,15,10,fc27,2026-09-12
1,231747,NaN,Kylian,Mbappé,91,ST,LW,Real Madrid,LALIGA EA SPORTS,France,...,15,34,24,13,5,7,11,6,fc27,2026-09-12
2,239085,NaN,Erling,Haaland,91,ST,NaN,Manchester City,Premier League,Norway,...,42,47,33,7,14,13,11,7,fc27,2026-09-12
3,192119,NaN,Thibaut,Courtois,90,GK,NaN,Real Madrid,LALIGA EA SPORTS,Belgium,...,20,18,16,87,89,78,90,90,fc27,2026-09-12
4,202126,NaN,Harry,Kane,90,ST,NaN,FC Bayern München,Bundesliga,England,...,46,44,42,8,10,11,14,11,fc27,2026-09-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19784,85140,Park Byeong Chan,Byeong Chan,Park,47,CDM,CM,Daejeon Hana,K League 1,Korea Republic,...,42,40,50,13,9,6,9,8,fc27,2026-09-12
19785,85153,Kim Ji Ho,Ji Ho,Kim,47,RW,RM,Daejeon Hana,K League 1,Korea Republic,...,19,22,29,9,13,7,11,13,fc27,2026-09-12
19786,259737,NaN,Haobam,Singh,47,CM,CAM CDM,FC Goa,ISL,India,...,39,43,41,14,12,15,14,6,fc27,2026-09-12
19787,275674,Ma Haoqi,Haoqi,Ma,47,RM,RW,Zhejiang Pro,CSL,China PR,...,15,22,26,9,8,8,12,12,fc27,2026-09-12
19788,275675,Ning Fangze,Fangze,Ning,47,LW,LM,Zhejiang Pro,CSL,China PR,...,32,40,43,7,9,5,5,14,fc27,2026-09-12

In [207]:
#coloquei o player_id como o indice
df.set_index(df["player_id"], inplace=True)
df

,player_id,common_name,first_name,last_name,overall_rating,position,alternate_positions,club,league,nationality,...,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,edition,snapshot_date,Coluna_Demo
player_id,,,,,,,,,,,,,,,,,,,,,
227203,227203,Alexia Putellas,Alexia,Putellas Segura,91,CM,CAM ST,London City,Barclays WSL,Spain,...,82,64,15,17,11,15,10,fc27,2026-09-12,0.493572
231747,231747,NaN,Kylian,Mbappé,91,ST,LW,Real Madrid,LALIGA EA SPORTS,France,...,34,24,13,5,7,11,6,fc27,2026-09-12,0.963524
239085,239085,NaN,Erling,Haaland,91,ST,NaN,Manchester City,Premier League,Norway,...,47,33,7,14,13,11,7,fc27,2026-09-12,0.688475
192119,192119,NaN,Thibaut,Courtois,90,GK,NaN,Real Madrid,LALIGA EA SPORTS,Belgium,...,18,16,87,89,78,90,90,fc27,2026-09-12,0.155914
202126,202126,NaN,Harry,Kane,90,ST,NaN,FC Bayern München,Bundesliga,England,...,44,42,8,10,11,14,11,fc27,2026-09-12,0.655665
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85140,85140,Park Byeong Chan,Byeong Chan,Park,47,CDM,CM,Daejeon Hana,K League 1,Korea Republic,...,40,50,13,9,6,9,8,fc27,2026-09-12,0.117119
85153,85153,Kim Ji Ho,Ji Ho,Kim,47,RW,RM,Daejeon Hana,K League 1,Korea Republic,...,22,29,9,13,7,11,13,fc27,2026-09-12,0.629946
259737,259737,NaN,Haobam,Singh,47,CM,CAM CDM,FC Goa,ISL,India,...,43,41,14,12,15,14,6,fc27,2026-09-12,0.617656
275674,275674,Ma Haoqi,Haoqi,Ma,47,RM,RW,Zhejiang Pro,CSL,China PR,...,22,26,9,8,8,12,12,fc27,2026-09-12,0.264665
275675,275675,Ning Fangze,Fangze,Ning,47,LW,LM,Zhejiang Pro,CSL,China PR,...,40,43,7,9,5,5,14,fc27,2026-09-12,0.816715

In [208]:
#resetei o indice de volta ao padrão
df.reset_index(drop=True,inplace=True)
df

,player_id,common_name,first_name,last_name,overall_rating,position,alternate_positions,club,league,nationality,...,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,edition,snapshot_date,Coluna_Demo
0,227203,Alexia Putellas,Alexia,Putellas Segura,91,CM,CAM ST,London City,Barclays WSL,Spain,...,82,64,15,17,11,15,10,fc27,2026-09-12,0.493572
1,231747,NaN,Kylian,Mbappé,91,ST,LW,Real Madrid,LALIGA EA SPORTS,France,...,34,24,13,5,7,11,6,fc27,2026-09-12,0.963524
2,239085,NaN,Erling,Haaland,91,ST,NaN,Manchester City,Premier League,Norway,...,47,33,7,14,13,11,7,fc27,2026-09-12,0.688475
3,192119,NaN,Thibaut,Courtois,90,GK,NaN,Real Madrid,LALIGA EA SPORTS,Belgium,...,18,16,87,89,78,90,90,fc27,2026-09-12,0.155914
4,202126,NaN,Harry,Kane,90,ST,NaN,FC Bayern München,Bundesliga,England,...,44,42,8,10,11,14,11,fc27,2026-09-12,0.655665
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19784,85140,Park Byeong Chan,Byeong Chan,Park,47,CDM,CM,Daejeon Hana,K League 1,Korea Republic,...,40,50,13,9,6,9,8,fc27,2026-09-12,0.117119
19785,85153,Kim Ji Ho,Ji Ho,Kim,47,RW,RM,Daejeon Hana,K League 1,Korea Republic,...,22,29,9,13,7,11,13,fc27,2026-09-12,0.629946
19786,259737,NaN,Haobam,Singh,47,CM,CAM CDM,FC Goa,ISL,India,...,43,41,14,12,15,14,6,fc27,2026-09-12,0.617656
19787,275674,Ma Haoqi,Haoqi,Ma,47,RM,RW,Zhejiang Pro,CSL,China PR,...,22,26,9,8,8,12,12,fc27,2026-09-12,0.264665
19788,275675,Ning Fangze,Fangze,Ning,47,LW,LM,Zhejiang Pro,CSL,China PR,...,40,43,7,9,5,5,14,fc27,2026-09-12,0.816715

In [209]:
#multiplos indices de maneira facilitada
df.set_index(["overall_rating", "player_id"])

                               common_name   first_name        last_name  \
overall_rating player_id
91             227203      Alexia Putellas       Alexia  Putellas Segura
               231747                  NaN       Kylian           Mbappé
               239085                  NaN       Erling          Haaland
90             192119                  NaN      Thibaut         Courtois
               202126                  NaN        Harry             Kane
...                                    ...          ...              ...
47             85140      Park Byeong Chan  Byeong Chan             Park
               85153             Kim Ji Ho        Ji Ho              Kim
               259737                  NaN       Haobam            Singh
               275674             Ma Haoqi        Haoqi               Ma
               275675          Ning Fangze       Fangze             Ning

                         position alternate_positions               club  \
overall_rating player_id
91             227203          CM              CAM ST        London City
               231747          ST                  LW        Real Madrid
               239085          ST                 NaN    Manchester City
90             192119          GK                 NaN        Real Madrid
               202126          ST                 NaN  FC Bayern München
...                           ...                 ...                ...
47             85140          CDM                  CM       Daejeon Hana
               85153           RW                  RM       Daejeon Hana
               259737          CM             CAM CDM             FC Goa
               275674          RM                  RW       Zhejiang Pro
               275675          LW                  LM       Zhejiang Pro

                                    league     nationality            gender  \
overall_rating player_id
91             227203         Barclays WSL           Spain  Women's Football
               231747     LALIGA EA SPORTS          France    Men's Football
               239085       Premier League          Norway    Men's Football
90             192119     LALIGA EA SPORTS         Belgium    Men's Football
               202126           Bundesliga         England    Men's Football
...                                    ...             ...               ...
47             85140            K League 1  Korea Republic    Men's Football
               85153            K League 1  Korea Republic    Men's Football
               259737                  ISL           India    Men's Football
               275674                  CSL        China PR    Men's Football
               275675                  CSL        China PR    Men's Football

                         preferred_foot  ...  defending_standing_tackle  \
overall_rating player_id                 ...
91             227203              Left  ...                         82
               231747             Right  ...                         34
               239085              Left  ...                         47
90             192119              Left  ...                         18
               202126             Right  ...                         44
...                                 ...  ...                        ...
47             85140              Right  ...                         40
               85153              Right  ...                         22
               259737             Right  ...                         43
               275674             Right  ...                         22
               275675             Right  ...                         40

                          defending_sliding_tackle  goalkeeping_diving  \
overall_rating player_id
91             227203                           64                  15
               231747                           24                  13
               239085                           33                   7
90             192119                           16                  87
               202126                           42                   8
...                                            ...                 ...
47             85140                            50                  13
               85153                            29                   9
               259737                           41                  14
               275674                           26                   9
               275675                           43                   7

                          goalkeeping_handling goalkeeping_kicking  \
overall_rating player_id
91             227203                       17                  11
               231747                        5                   7
               239085                       14                  13
90             192119                       89                  78
               202126                       10                  11
...                                        ...                 ...
47             85140                         9                   6
               85153                        13                   7
               259737                       12                  15
               275674                        8                   8
               275675                        9                   5

                         goalkeeping_positioning  goalkeeping_reflexes  \
overall_rating player_id
91             227203                         15                    10
               231747                         11                     6
               239085                         11                     7
90             192119                         90                    90
               202126                         14                    11
...                                          ...                   ...
47             85140                           9                     8
               85153                          11                    13
               259737                         14                     6
               275674                         12                    12
               275675                          5                    14

                          edition  snapshot_date  Coluna_Demo
overall_rating player_id
91             227203        fc27     2026-09-12     0.493572
               231747        fc27     2026-09-12     0.963524
               239085        fc27     2026-09-12     0.688475
90             192119        fc27     2026-09-12     0.155914
               202126        fc27     2026-09-12     0.655665
...                           ...            ...          ...
47             85140         fc27     2026-09-12     0.117119
               85153         fc27     2026-09-12     0.629946
               259737        fc27     2026-09-12     0.617656
               275674        fc27     2026-09-12     0.264665
               275675        fc27     2026-09-12     0.816715

[19789 rows x 59 columns]

In [213]:
#agrupa os valores iguais de uma coluna
overall_df = df.groupby("overall_rating")

In [214]:
#gera a maioria das estátisticas que possam ser interessantes
overall_df.describe()

               player_id                                                    \
                   count           mean           std       min        25%
overall_rating
47                  13.0  124993.153846  83055.680377   71329.0   83059.00
48                  52.0  117692.807692  77106.625589   70794.0   77902.25
49                  42.0  123859.214286  83521.271997   70647.0   76744.25
50                  66.0  114472.045455  74902.767139   70615.0   76833.50
51                  88.0  119529.818182  76605.048753   70514.0   76854.25
52                 131.0  120411.030534  76977.028391   70279.0   77191.00
53                 217.0  120703.539171  75722.609290   70142.0   78401.00
54                 224.0  140265.459821  86004.018452   69986.0   79765.50
55                 274.0  134006.656934  82271.635522   70269.0   78959.00
56                 306.0  135361.967320  83577.912772   70281.0   78944.00
57                 389.0  137110.164524  83807.392726   70045.0   79365.00
58                 537.0  146405.722533  86308.151281   70442.0   80289.00
59                 514.0  147443.750973  87024.059869   70063.0   79896.25
60                 706.0  158190.590652  88166.398654   70065.0   79444.50
61                 696.0  166190.675287  87936.840538   70006.0   80489.25
62                 894.0  169569.667785  87880.440520   69971.0   79957.50
63                1033.0  182391.419167  86033.099358   70025.0   82303.00
64                1138.0  195151.145870  82936.386333   69965.0   83515.50
65                1232.0  198041.305195  82097.968391   69990.0   83600.00
66                1168.0  204045.449486  77947.118766   70026.0   86448.50
67                1217.0  205277.098603  76691.183203   69963.0   87971.00
68                1314.0  213254.402588  71433.466787   70005.0  204860.25
69                1084.0  214024.420664  69697.595513   69957.0  209694.00
70                1045.0  219647.387560  66708.884843   69983.0  215123.00
71                 806.0  221654.929280  62185.613227   70020.0  215260.50
72                 804.0  230095.240050  54582.780202   70675.0  223794.75
73                 656.0  225138.922256  58999.687156   70012.0  217533.00
74                 588.0  236101.418367  49134.973240   69967.0  228248.25
75                 469.0  231638.302772  52618.516983   69997.0  225926.00
76                 422.0  236204.732227  43982.687407   70497.0  227132.50
77                 354.0  230400.946328  51301.080618   70726.0  223615.50
78                 321.0  235672.996885  45226.220551   70888.0  227201.00
79                 198.0  236285.136364  40083.089428   70004.0  225125.25
80                 191.0  241348.256545  34303.097783   71494.0  229068.50
81                 155.0  237256.000000  35617.604372   70415.0  226717.50
82                 119.0  238238.100840  24930.137206  165153.0  220633.50
83                  91.0  243402.373626  23504.668014  193080.0  227200.00
84                  71.0  237456.169014  38578.577477   20801.0  229529.00
85                  61.0  237852.180328  21779.557343  177003.0  227110.00
86                  30.0  245095.233333  14156.082515  222665.0  235125.75
87                  28.0  239145.500000  19465.423312  207865.0  227115.75
88                  18.0  240644.388889  22054.949713  200389.0  233658.75
89                  13.0  236673.692308  29198.533218  158023.0  230621.00
90                  11.0  239126.181818  24298.025219  192119.0  231654.50
91                   3.0  232678.333333   5995.499757  227203.0  229475.00

                                              skill_moves            ...  \
                     50%        75%       max       count      mean  ...
overall_rating                                                       ...
47               83877.0   85153.00  275675.0        13.0  1.923077  ...
48               83722.0   85164.00  278937.0        52.0  1.903846  ...
49               79972.5   85855.50  278670.0        42.0  1.809524  ...
50               82062.0   85828.50  279563.0        66.0  1.742424  ...
51               83106.0   88079.25  279660.0        88.0  1.647727  ...
52               82693.0   87507.50  279584.0       131.0  1.748092  ...
53               83327.0   88128.00  279938.0       217.0  1.852535  ...
54               85917.5  251348.75  279785.0       224.0  1.888393  ...
55               84220.0  240258.00  279588.0       274.0  1.890511  ...
56               84964.5  245117.75  279929.0       306.0  1.879085  ...
57               85255.0  242698.00  279806.0       389.0  1.974293  ...
58               86591.0  251261.00  279650.0       537.0  1.985102  ...
59               85442.5  255544.25  279787.0       514.0  2.048638  ...
60               87048.5  256978.50  279907.0       706.0  2.135977  ...
61               88442.5  259175.00  279714.0       696.0  2.238506  ...
62              204535.0  257885.50  279827.0       894.0  2.237136  ...
63              228355.0  261753.00  279897.0      1033.0  2.290416  ...
64              237994.5  263365.00  279868.0      1138.0  2.318102  ...
65              240970.5  262970.50  279909.0      1232.0  2.339286  ...
66              241749.5  262642.75  279926.0      1168.0  2.380137  ...
67              240233.0  262024.00  279948.0      1217.0  2.449466  ...
68              243323.0  262845.00  279942.0      1314.0  2.417047  ...
69              240973.0  261435.50  279933.0      1084.0  2.416974  ...
70              243787.0  264421.00  279925.0      1045.0  2.447847  ...
71              241939.0  262706.00  279934.0       806.0  2.538462  ...
72              245204.5  263677.75  279877.0       804.0  2.575871  ...
73              242876.0  264212.00  279885.0       656.0  2.667683  ...
74              247385.0  265643.75  279841.0       588.0  2.642857  ...
75              245977.0  264330.00  279836.0       469.0  2.690832  ...
76              244626.0  264307.50  279523.0       422.0  2.793839  ...
77              243263.0  263451.75  279173.0       354.0  2.785311  ...
78              245371.0  264950.00  278773.0       321.0  2.806854  ...
79              242646.5  264195.25  279709.0       198.0  2.772727  ...
80              243769.0  264994.50  279811.0       191.0  2.869110  ...
81              243241.0  262128.00  279699.0       155.0  2.864516  ...
82              239761.0  259916.00  279812.0       119.0  2.907563  ...
83              244263.0  265641.00  279532.0        91.0  3.010989  ...
84              242896.0  259809.50  277954.0        71.0  3.323944  ...
85              241096.0  248343.00  277179.0        61.0  3.163934  ...
86              244641.5  255097.75  278046.0        30.0  3.300000  ...
87              234409.5  256844.50  278219.0        28.0  3.071429  ...
88              239186.5  256440.50  276359.0        18.0  3.111111  ...
89              238794.0  252145.00  279799.0        13.0  3.615385  ...
90              246219.0  252112.50  277643.0        11.0  3.727273  ...
91              231747.0  235416.00  239085.0         3.0  4.333333  ...

               goalkeeping_reflexes       Coluna_Demo                      \
                                75%   max       count      mean       std
overall_rating
47                            14.00  45.0        13.0  0.489061  0.252466
48                            13.00  52.0        52.0  0.516769  0.323333
49                            15.00  53.0        42.0  0.491505  0.273899
50                            48.00  55.0        66.0  0.458210  0.303812
51                            51.00  59.0        88.0  0.537686  0.288972
52                            47.50  60.0       131.0  0.477344  0.278535
53                            15.00  63.0       217.0  0.518021  0.304304
54                            14.00  59.0       224.0  0.514093  0.287444
55                            14.00  63.0       274.0  0.523069  0.296090
56                            15.00  65.0       306.0  0.471256  0.298648
57                            14.00  63.0       389.0  0.507515  0.295907
58                            14.00  67.0       537.0  0.501817  0.291901
59                            14.00  64.0       514.0  0.511603  0.281140
60                            14.00  66.0       706.0  0.489756  0.294887
61                            14.00  68.0       696.0  0.496392  0.292585
62                            13.00  69.0       894.0  0.504122  0.290590
63                            14.00  69.0      1033.0  0.507554  0.293132
64                            13.00  69.0      1138.0  0.497530  0.294280
65                            13.00  75.0      1232.0  0.494916  0.284629
66                            13.00  74.0      1168.0  0.501894  0.292432
67                            13.00  74.0      1217.0  0.495660  0.293570
68                            13.00  76.0      1314.0  0.503794  0.290905
69                            14.00  75.0      1084.0  0.498982  0.288842
70                            13.00  76.0      1045.0  0.489331  0.285411
71                            13.00  77.0       806.0  0.483820  0.286045
72                            13.00  78.0       804.0  0.517055  0.284524
73                            13.00  79.0       656.0  0.493084  0.289626
74                            14.00  80.0       588.0  0.499820  0.291333
75                            13.00  79.0       469.0  0.497490  0.295230
76                            13.00  79.0       422.0  0.519428  0.280702
77                            13.00  82.0       354.0  0.506469  0.284413
78                            13.00  81.0       321.0  0.500402  0.289591
79                            13.75  83.0       198.0  0.494539  0.291529
80                            14.00  85.0       191.0  0.481348  0.284418
81                            14.00  85.0       155.0  0.534007  0.306609
82                            14.00  86.0       119.0  0.482346  0.279874
83                            14.00  86.0        91.0  0.491294  0.301310
84                            13.00  85.0        71.0  0.485645  0.298458
85                            14.00  88.0        61.0  0.532727  0.277336
86                            13.00  88.0        30.0  0.550701  0.245089
87                            14.50  89.0        28.0  0.421160  0.308261
88                            14.00  88.0        18.0  0.490065  0.310156
89                            12.00  90.0        13.0  0.665077  0.205101
90                            12.00  90.0        11.0  0.385716  0.308844
91                             8.50  10.0         3.0  0.715190  0.236112


                     min       25%       50%       75%       max
overall_rating
47              0.037769  0.306798  0.548704  0.629946  0.871174
48              0.013062  0.172018  0.589377  0.793331  0.973856
49              0.044200  0.236422  0.487406  0.697894  0.976449
50              0.030886  0.214181  0.400401  0.745111  0.996410
51              0.010531  0.303068  0.544408  0.766971  0.995539
52              0.000047  0.250003  0.427386  0.725672  0.991389
53              0.007786  0.253277  0.505031  0.818886  0.998642
54              0.003076  0.291831  0.515943  0.739085  0.999462
55              0.003263  0.260723  0.544038  0.791203  0.999914
56              0.001260  0.197405  0.462990  0.720819  0.998694
57              0.004284  0.254262  0.504127  0.777632  0.999054
58              0.000865  0.259137  0.509708  0.748995  0.999751
59              0.004553  0.258314  0.511824  0.757912  0.998837
60              0.003252  0.224628  0.475887  0.760042  0.999849
61              0.002988  0.239764  0.488193  0.745326  0.999891
62              0.000570  0.255680  0.514144  0.762709  0.995762
63              0.001483  0.248558  0.511364  0.766555  0.999904
64              0.000123  0.228425  0.505427  0.755935  0.999138
65              0.000533  0.244690  0.500179  0.732946  0.999884
66              0.000066  0.257733  0.501016  0.762237  0.999937
67              0.001923  0.232039  0.480756  0.761795  0.999467
68              0.001502  0.247935  0.507108  0.765916  0.997164
69              0.001174  0.258717  0.501390  0.744754  0.998435
70              0.001618  0.257295  0.479746  0.736794  0.999971
71              0.002896  0.225899  0.488630  0.725130  0.999267
72              0.000145  0.282081  0.517315  0.755998  0.999188
73              0.000444  0.247000  0.484277  0.745352  0.999576
74              0.000198  0.231615  0.489746  0.741499  0.998476
75              0.003578  0.251455  0.500260  0.733455  0.997510
76              0.001468  0.283493  0.515342  0.765067  0.999103
77              0.001894  0.262390  0.503307  0.747354  0.996806
78              0.004598  0.267595  0.489355  0.766210  0.992723
79              0.002273  0.250452  0.473263  0.772675  0.997256
80              0.001198  0.231112  0.499994  0.724539  0.979856
81              0.013877  0.246366  0.522226  0.822048  0.998694
82              0.026976  0.265658  0.454100  0.763098  0.996973
83              0.013830  0.209465  0.522529  0.718915  0.996510
84              0.011725  0.222081  0.468140  0.726038  0.990214
85              0.010738  0.316311  0.570048  0.771704  0.998854
86              0.021891  0.392171  0.552263  0.749533  0.947936
87              0.009465  0.151708  0.360230  0.695005  0.994024
88              0.007049  0.255712  0.482880  0.774898  0.945677
89              0.276718  0.498679  0.703376  0.791819  0.973111
90              0.066670  0.123093  0.240660  0.635950  0.944349
91              0.493572  0.591023  0.688475  0.825999  0.963524

[45 rows x 368 columns]

In [222]:
#operação booleana para ver bons jogadores atacantes
cond1 = df["shooting"] > 80
cond2 = df["dribbling"] > 85
df[cond1 & cond2]["overall_rating"]

0      91
1      91
3      90
5      90
7      90
9      90
11     90
12     90
13     90
14     89
16     89
17     89
19     89
20     89
21     89
22     89
25     89
26     89
27     88
30     88
31     88
35     88
36     88
39     88
40     88
41     88
42     88
46     87
47     87
49     87
53     87
58     87
59     87
62     87
65     87
67     87
68     87
72     87
88     86
89     86
94     86
98     86
101    86
111    85
119    85
127    85
155    85
159    85
160    85
169    84
175    84
190    84
200    84
276    83
344    82
418    82
940    79
Name: overall_rating, dtype: int64

In [223]:
#verifica se o jogador eh bom em atirar ou em driblar
df[cond1 | cond2]["overall_rating"]

0       91
1       91
2       91
3       90
4       90
        ..
1269    78
1295    78
1297    78
1498    77
2626    74
Name: overall_rating, Length: 255, dtype: int64

In [224]:
df.to_csv("new_players.csv")