In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(101)

In [3]:
df = pd.DataFrame(np.random.randn(5, 4), index= 'A B C D E'.split(), columns= 'W X Y Z'.split())

In [4]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [8]:
#analisa a coluna escrita
df["W"]

A   -0.993263
B    1.025984
C    2.154846
D    0.147027
E   -0.925874
Name: W, dtype: float64

In [11]:
#Quando se analisa a coluna escrita, os valores vem no formato de Series
type(df["W"])

pandas.Series

In [12]:
#Enquanto o df segue sendo DataFrame
type(df)

pandas.DataFrame

In [14]:
#Permite analisar um conjunto de colunas
df[["W", "Z"]]

          W         Z
A -0.993263  0.000366
B  1.025984  0.649826
C  2.154846 -0.346419
D  0.147027  1.024810
E -0.925874  0.610478

In [15]:
#não recomendado, pois pode ser confundido com uma função
df.W

A   -0.993263
B    1.025984
C    2.154846
D    0.147027
E   -0.925874
Name: W, dtype: float64

In [16]:
#tenta criar uma nova coluna sem dados, erro
df["NEW"]

KeyError: 'NEW'

In [17]:
#cria uma nova coluna somando os dados de outras colunas
df["NEW"] = df["W"] + df["X"]

In [18]:
df

          W         X         Y         Z       NEW
A -0.993263  0.196800 -1.136645  0.000366 -0.796464
B  1.025984 -0.156598 -0.031579  0.649826  0.869386
C  2.154846 -0.610259 -0.755325 -0.346419  1.544588
D  0.147027 -0.479448  0.558769  1.024810 -0.332421
E -0.925874  1.862864 -1.133817  0.610478  0.936990

In [19]:
#remove a coluna criada apenas para exibição(implace tem que estar True para afetar a df diretamente)
df.drop("NEW", axis = 1)

          W         X         Y         Z
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

In [20]:
df

          W         X         Y         Z       NEW
A -0.993263  0.196800 -1.136645  0.000366 -0.796464
B  1.025984 -0.156598 -0.031579  0.649826  0.869386
C  2.154846 -0.610259 -0.755325 -0.346419  1.544588
D  0.147027 -0.479448  0.558769  1.024810 -0.332421
E -0.925874  1.862864 -1.133817  0.610478  0.936990

In [21]:
#o que foi dito anteriormente eh aplicado aqui
df.drop("NEW", axis = 1, inplace=True)

In [22]:
df

          W         X         Y         Z
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

In [25]:
#localiza a linha descrita
df.loc["A"]

W   -0.993263
X    0.196800
Y   -1.136645
Z    0.000366
Name: A, dtype: float64

In [26]:
#localiza um valor especifico ao definir linha e coluna
df.loc["A", "W"]

np.float64(-0.993263499973366)

In [28]:
#localiza apenas os valores das linhas e colunas especificadas
df.loc[["A", "B"], ["X", "Y", "Z"]]

          X         Y         Z
A  0.196800 -1.136645  0.000366
B -0.156598 -0.031579  0.649826

In [30]:
#usa valores inteiros para analisar como se fosse uma matriz
df.iloc[1:4, 2:]

          Y         Z
B -0.031579  0.649826
C -0.755325 -0.346419
D  0.558769  1.024810