In [1]:
import numpy as np
import pandas as pd

In [2]:
d = {"A": [1, 2, np.nan], "B": [5, np.nan, np.nan], "C": [1, 2, 3]}

In [3]:
df = pd.DataFrame(d)

In [5]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [8]:
#retira as linhas/colunas com valores nulos
df.dropna()

     A    B  C
0  1.0  5.0  1

In [10]:
#remove apenas linhas/colunas com mais de 2 nulos
df.dropna(thresh = 2)

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [11]:
#preenche os dados nulos com o valor definido
df.fillna(value="fill na")

         A        B  C
0      1.0      5.0  1
1      2.0  fill na  2
2  fill na  fill na  3

In [13]:
#preenche os dados nulos na coluna A com a media dos valores antecedores 
df["A"].fillna(value=df["A"].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [15]:
#No video, ffill era um das opcoes de um atributo do fillna chamado "method", agora ffill eh um metodo separado
#preenche os dados nulos com valores que o antecedem bom pra ser usado com analise em tempos reais
df.ffill()

     A    B  C
0  1.0  5.0  1
1  2.0  5.0  2
2  2.0  5.0  3

In [ ]:
#aplica o dropna no df
df.dropna(inplace = True)