In [2]:
import numpy as np
import pandas as pd

In [3]:
data = {"Empresa": ["GOOG", "GOOG", "MSFT", "MSFT", "FB", "FB"],
        "Nome": ["Sam", "Charlie", "Amy", "Vanessa", "Carl", "Sarah"],
        "Venda": [200, 120, 340, 124, 245, 350]}

In [4]:
df = pd.DataFrame(data)

In [5]:
df

  Empresa     Nome  Venda
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    245
5      FB    Sarah    350

In [7]:
#agrupa os valores não distintos em um só
group = df.groupby("Empresa")
group

In [8]:
#soma todos os valores dentro do agrupamento
group.sum()

               Nome  Venda
Empresa
FB        CarlSarah    595
GOOG     SamCharlie    320
MSFT     AmyVanessa    464

In [9]:
#procura o valor minimo de cada grupo
group.min()

            Nome  Venda
Empresa
FB          Carl    245
GOOG     Charlie    120
MSFT         Amy    124

In [10]:
#procura o valor maximo de cada grupo
group.max()

            Nome  Venda
Empresa
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340

In [14]:
#faz a media dos numeros(caso o numeric_only fosse False, daria erro, por haver divisao de str)
group.mean(numeric_only=True)

         Venda
Empresa
FB       297.5
GOOG     160.0
MSFT     232.0

In [12]:
#passa grande quantidade de informações importantes
group.describe()

        Venda
        count   mean         std    min     25%    50%     75%    max
Empresa
FB        2.0  297.5   74.246212  245.0  271.25  297.5  323.75  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [16]:
#mostra quantos dados existem dentro de cada grupo
group.count()

         Nome  Venda
Empresa
FB          2      2
GOOG        2      2
MSFT        2      2

In [22]:
#faz um agrupamento de valores sem similaridades, resultando em um df com o indice sendo o valor definido
group2 = df.groupby(by="Nome")

In [23]:
group2

In [24]:
group2.sum()

        Empresa  Venda
Nome
Amy        MSFT    340
Carl         FB    245
Charlie    GOOG    120
Sam        GOOG    200
Sarah        FB    350
Vanessa    MSFT    124