In [1]:
import numpy as np
import pandas as pd

In [12]:
df = pd.DataFrame({"col1": [1, 2, 3, 4],
                  "col2": [444, 555, 666, 444],
                  "col3": ["abc", "def", "ghi", "xyz"]})
df.head()

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [13]:
#unique mostra os numeros distintos presentes na linha/coluna
df["col2"].unique()

array([444, 555, 666])

In [14]:
np.unique(df["col2"])

array([444, 555, 666])

In [15]:
#com isso podemos ver o numero de numeros distintos dentro da linha/coluna
len(df["col2"].unique())

3

In [16]:
df["col2"].nunique()

3

In [17]:
#com isso podemos ver ambos os acima, mostrando os numeros distintos e a quantidade de vezes que aparecem
df["col2"].value_counts()

col2
444    2
555    1
666    1
Name: count, dtype: int64

In [21]:
df[(df["col1"] > 2) & (df["col2"] == 444)]

   col1  col2 col3
3     4   444  xyz

In [24]:
def vezes2(x):
    return x*2

In [25]:
df["col1"].sum()

np.int64(10)

In [26]:
#apply aplica funcoes em cada um dos elementos da Serie/DataFrame
df["col1"].apply(vezes2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [27]:
#aplica as funcoes, mesmo as lambda criadas dentro do apply
df["col1"].apply(lambda x: x*x)

0     1
1     4
2     9
3    16
Name: col1, dtype: int64

In [29]:
#del deleta linhas/colunas
del(df["col2"])

In [30]:
df

   col1 col3
0     1  abc
1     2  def
2     3  ghi
3     4  xyz

In [31]:
#mostra as colunas do DataFrame
df.columns

Index(['col1', 'col3'], dtype='str')

In [32]:
#mostra os indices do Dataframe
df.index

RangeIndex(start=0, stop=4, step=1)

In [33]:
#ordena os valores da coluna/linha colocada no by, usa inplace como False
df.sort_values(by="col1")

   col1 col3
0     1  abc
1     2  def
2     3  ghi
3     4  xyz

In [34]:
#verifica os valores nulos
df.isnull()

    col1   col3
0  False  False
1  False  False
2  False  False
3  False  False

In [36]:
df = pd.DataFrame({"col1": [1, 2, 3, np.nan],
                  "col2": [np.nan, 555, 666, 444],
                  "col3": ["abc", "def", "ghi", "xyz"]})
df.head()

   col1   col2 col3
0   1.0    NaN  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   NaN  444.0  xyz

In [37]:
#inplace false por padrao
df["col1"].fillna(value=df["col1"].mean())

0    1.0
1    2.0
2    3.0
3    2.0
Name: col1, dtype: float64

In [39]:
data = {"A": ["foo", "foo", "foo", "bar", "bar", "bar"],
        "B": ["one", "one", "two", "two", "one", "one"],
        "C": ["x", "y", "x", "y", "x", "y"],
        "D": [1 , 3, 2, 5, 4, 1]}
df = pd.DataFrame(data)

In [40]:
df

     A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [41]:
#cria uma tabela dinâmica, transformando valores repetidos e não nulos em indices multi-niveis
df.pivot_table(values="D", index=["A", "B"], columns=["C"])

C          x    y
A   B
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN