In [1]:
import numpy as np
import pandas as pd

In [7]:
from numpy.random import randn
np.random.seed(101)

In [8]:
df = pd.DataFrame(randn(5, 4), index="A B C D E".split(), columns= "W X Y Z".split())

In [9]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [10]:
#devolve booleanas para usar em analise de dados
df > 0

       W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [11]:
bol = df > 0

In [12]:
#ordena os valores por quais são verdadeiros e falsos
df[bol]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [13]:
#mesma coisa com o de cima, mas com outra condição
df[df["W"] > 0]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [14]:
#olha a coluna enquanto se aplica uma booleana para ordenacao
df[df["W"] > 0]["Y"]

A    0.907969
B   -0.848077
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [15]:
#mesmo processo do acima, mas com uma outra ordem
bol = df["W"] > 0
df2 = df[bol]
df2["Y"]

A    0.907969
B   -0.848077
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [16]:
#Nao funciona por causa do and
df[(df["W"] > 0) and (df["Y"] > 1)]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [17]:
#forma correta de se aplicar a comparação "e" entre duas booleanas
df[(df["W"] > 0) & (df["Y"] > 1)]

          W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [18]:
#Nao funciona por causa do or
df[(df["W"] > 0) or (df["Y"] > 1)]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [19]:
#forma correta de se aplicar a comparação "or" entre duas booleanas
df[(df["W"] > 0) | (df["Y"] > 1)]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [22]:
#Caso o indice nao seja o padrão(numeros), ele transforma de volta para o padrão, transformando o indice antigo em uma coluna
df.reset_index(inplace=True)

In [23]:
df

  index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [24]:
col = "RS RJ SP AM  SC".split()

In [25]:
df["Estados"] = col

In [26]:
df

  index         W         X         Y         Z Estados
0     A  2.706850  0.628133  0.907969  0.503826      RS
1     B  0.651118 -0.319318 -0.848077  0.605965      RJ
2     C -2.018168  0.740122  0.528813 -0.589001      SP
3     D  0.188695 -0.758872 -0.933237  0.955057      AM
4     E  0.190794  1.978757  2.605967  0.683509      SC

In [28]:
#define a coluna selecionada como indice
df.set_index("Estados", inplace=True)

In [29]:
df

        index         W         X         Y         Z
Estados
RS          A  2.706850  0.628133  0.907969  0.503826
RJ          B  0.651118 -0.319318 -0.848077  0.605965
SP          C -2.018168  0.740122  0.528813 -0.589001
AM          D  0.188695 -0.758872 -0.933237  0.955057
SC          E  0.190794  1.978757  2.605967  0.683509