In [1]:
import numpy as np
import pandas as pd

In [20]:
#Criacao das labels
indice = ["Fruta", "Preco/KG", "Estoque", "Fornecedor", "Validade"]
indice

['Fruta', 'Preco/KG', 'Estoque', 'Fornecedor', 'Validade']

In [36]:
#criacao dos dados
dados = ["Abacate", 4, 20, "Coppercitrus", 2], ["Banana", 6.99, 10, "Bananasportao", 3], ["Laranja", 1.78, 40.8, "Citropack", 5]

In [37]:
#Labels colocadas em uma Serie
ser0 = pd.Series(indice)
ser0

0         Fruta
1      Preco/KG
2       Estoque
3    Fornecedor
4      Validade
dtype: str

In [114]:
#DataFrame criado atraves dos dados junto das labels
df = pd.DataFrame(dados,columns=ser0)
#coloca Fruta como indice
df.set_index("Fruta", inplace=True)
df

         Preco/KG  Estoque     Fornecedor  Validade
Fruta
Abacate      4.00     20.0   Coppercitrus         2
Banana       6.99     10.0  Bananasportao         3
Laranja      1.78     40.8      Citropack         5

In [47]:
#cria uma nova coluna que é produto do preço com a quantidade no estoque
df["PrecoTotal"] = df["Preco/KG"]*df["Estoque"]
df

         Preco/KG  Estoque     Fornecedor  Validade  PrecoTotal
Fruta
Abacate      4.00     20.0   Coppercitrus         2      80.000
Banana       6.99     10.0  Bananasportao         3      69.900
Laranja      1.78     40.8      Citropack         5      72.624

In [48]:
#localiza uma unica linha e passa por ela como uma Serie
df.loc["Banana"]

Preco/KG               6.99
Estoque                10.0
Fornecedor    Bananasportao
Validade                  3
PrecoTotal             69.9
Name: Banana, dtype: object

In [75]:
#criacao de um segundo DataFrame para concatenar
df2 = pd.DataFrame({"Fruta": ["Amora"],
                    "Preco/KG": [np.nan],
                   "Estoque": [np.nan],
                   "Fornecedor": [np.nan],
                   "Validade": [np.nan],
                   "PrecoTotal": [np.nan]})
df2.set_index("Fruta", inplace=True)
df2

       Preco/KG  Estoque  Fornecedor  Validade  PrecoTotal
Fruta
Amora       NaN      NaN         NaN       NaN         NaN

In [78]:
#cria sem querer duas instancias da df2 dentro da df
df = pd.concat([df,df2])
df = pd.concat([df,df2])
df

         Preco/KG  Estoque     Fornecedor  Validade  PrecoTotal
Fruta
Abacate      4.00     20.0   Coppercitrus       2.0      80.000
Banana       6.99     10.0  Bananasportao       3.0      69.900
Laranja      1.78     40.8      Citropack       5.0      72.624
Amora         NaN      NaN            NaN       NaN         NaN
Amora         NaN      NaN            NaN       NaN         NaN

In [84]:
#deleta todas as instancias da df2
df.drop(labels="Amora", inplace=True)
df

         Preco/KG  Estoque     Fornecedor  Validade  PrecoTotal
Fruta
Abacate      4.00     20.0   Coppercitrus       2.0      80.000
Banana       6.99     10.0  Bananasportao       3.0      69.900
Laranja      1.78     40.8      Citropack       5.0      72.624

In [87]:
#corrige o erro, fazendo apenas uma unica instancia
df = pd.concat([df,df2])
df

         Preco/KG  Estoque     Fornecedor  Validade  PrecoTotal
Fruta
Abacate      4.00     20.0   Coppercitrus       2.0      80.000
Banana       6.99     10.0  Bananasportao       3.0      69.900
Laranja      1.78     40.8      Citropack       5.0      72.624
Amora         NaN      NaN            NaN       NaN         NaN

In [90]:
#enche a parte null da Amora, Preco/KG com um valor especifico
df.fillna({"Preco/KG": 30}, inplace=True)

         Preco/KG  Estoque     Fornecedor  Validade  PrecoTotal
Fruta
Abacate      4.00     20.0   Coppercitrus       2.0      80.000
Banana       6.99     10.0  Bananasportao       3.0      69.900
Laranja      1.78     40.8      Citropack       5.0      72.624
Amora       30.00      NaN            NaN       NaN         NaN

In [93]:
#modifica o nome da coluna Estoque para fazer mais sentido
df.rename(columns={"Estoque": "Estoque(KG)"}, inplace=True)

In [94]:
df

         Preco/KG  Estoque(KG)     Fornecedor  Validade  PrecoTotal
Fruta
Abacate      4.00         20.0   Coppercitrus       2.0      80.000
Banana       6.99         10.0  Bananasportao       3.0      69.900
Laranja      1.78         40.8      Citropack       5.0      72.624
Amora       30.00          NaN            NaN       NaN         NaN

In [100]:
#enche as partes nulas da Amora com dados da Laranja
df.ffill(inplace = True)

         Preco/KG  Estoque(KG)     Fornecedor  Validade  PrecoTotal
Fruta
Abacate      4.00         20.0   Coppercitrus       2.0      80.000
Banana       6.99         10.0  Bananasportao       3.0      69.900
Laranja      1.78         40.8      Citropack       5.0      72.624
Amora       30.00         40.8      Citropack       5.0      72.624

In [101]:
#Analise de Dados
#Analisa os valores unicos dentro da coluna Validade
df["Validade"].unique()

array([2., 3., 5.])

In [102]:
#Analisa o num de valores unicos na coluna Validade
df["Validade"].nunique()

3

In [103]:
#Analisa a quantidade de valores que se repetem na coluna Validade
df["Validade"].value_counts()

Validade
5.0    2
2.0    1
3.0    1
Name: count, dtype: int64

In [104]:
#Calcula a media de todos os valores dentro da coluna PrecoTotal
df["PrecoTotal"].mean()

np.float64(73.787)

In [105]:
#Calcula a soma dentro do PrecoTotal
df["PrecoTotal"].sum()

np.float64(295.148)

In [111]:
#Procura o maior valor dentro de PrecoTotal
df["PrecoTotal"].max()

np.float64(80.0)

In [112]:
#Procura o menor valor
df["PrecoTotal"].min()

np.float64(69.9)

In [113]:
#exporta o df para um arquivo chamado Frutas.csv
df.to_csv("Frutas.csv")